---
  version: '3.7'
  
  x-config:
    &secrets-config
    secrets:
      - source: tomcat_ssl_crt
        target: /home/spring/tomcat-wildcard-ssl.crt
      - source: tomcat_ssl_key
        target: /home/spring/tomcat-wildcard-ssl.key
        
  secrets:
    tomcat_ssl_crt:
      file: ./docker/certificates/tomcat-wildcard.crt
    tomcat_ssl_key:
      file: ./docker/certificates/tomcat-wildcard.key

  services:
    mlr-notification-service:
      build: .
      image: mlr-notification-service
      ports:
        - "6025:6025"
      << : *secrets-config
      volumes: 
      - ./docker/certificates/import_certs:/certificates:ro
      env_file:
        - ./docker/config.env
        - ./docker/secrets.env
      
    mlr-notification-service-local-dev:
      build: .
      image: mlr-notification-service
      network_mode: "host"
      ports:
        - "6025:6025"
      << : *secrets-config
      volumes: 
        - ./docker/certificates/import_certs:/certificates:ro
      env_file:
        - ./docker/config.env
        - ./docker/secrets.env

    mlr-notification-service-debug:
      build: .
      image: mlr-notification-service
      network_mode: "host"
      ports:
        - "6025:6025"
        - "8000:8000"
      << : *secrets-config
      volumes: 
        - ./docker/certificates/import_certs:/certificates:ro
      environment:
        - JAVA_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n"
      env_file:
        - ./docker/config.env
        - ./docker/secrets.env