mlrNotificationServicePwd: ${MLR_NOTIFICATION_SERVICE_PWD}
mlrEmailTemplateFrom: ${MLR_NOTIFICATION_EMAIL_FROM}
spring:
  mail:
    host: ${MLR_NOTIFICATION_EMAIL_HOST}
    port: ${MLR_NOTIFICATION_EMAIL_PORT}
    defaultEncoding: UTF-8
    protocol: smtp
  profiles:
    active: default, swagger

security:
  basic:
    enabled: false
  oauth2:
    resource:
      filter-order: 3
      id: ${oauthResourceId:oauth2-resource}
      jwt:
        keyUri: ${authPublicKeyUrl}
  require-ssl: true

server:
    port: ${serverPort:8443}
    ssl:
        key-store: ${keystoreLocation}
        key-store-password: ${keystorePassword}
        key-password: ${keystorePassword}
        key-alias: ${keystoreSSLKey:tomcat}
        
keystoreLocation : ${keystoreLocation}
keystorePassword: ${keystorePassword}

