mlrNotificationServicePwd: ${MLR_NOTIFICATION_SERVICE_PWD}
mlrEmailTemplateFrom: ${MLR_NOTIFICATION_EMAIL_FROM}
spring:
  mail:
    host: ${MLR_NOTIFICATION_EMAIL_HOST}
    port: ${MLR_NOTIFICATION_EMAIL_PORT}
    defaultEncoding: UTF-8
    protocol: smtp
  profiles:
    active: default, swagger

security:
  require-ssl: true
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ${oauthClientId}
      clientSecret: ${oauthClientSecret}
      accessTokenUri: ${oauthClientAccessTokenUri}
      userAuthorizationUri: ${oauthClientAuthorizationUri}
    resource:
      id: ${oauthResourceId}
      jwt:
        keyUri: ${oauthResourceTokenKeyUri}

server:
    port: ${serverPort:8443}
    ssl:
        key-store: ${keystoreLocation}
        key-store-password: ${keystorePassword}
        key-password: ${keystorePassword}
        key-alias: ${keystoreSSLKey:tomcat}

